### ISSUE TITLE
DNSRecords that don't contain Domain Suffix aren't reconciled properly

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/kubeflare#18]
Example:

```yaml
apiVersion: crds.kubeflare.io/v1alpha1
kind: DNSRecord
metadata:
  name: diamon-codeserver-test.repldev.com
spec:
  zone: repldev.com
  record:
    type: "A"
    name: "diamon-codeserver-test"
    content: "34.94.103.105"
    proxied: true
    ttl: 3600
```

The above is created, but never will never be updated properly due to:

https://github.com/replicatedhq/kubeflare/blob/master/pkg/controller/dnsrecord/dns_records.go#L37-L40

`desiredRecord.Name` never matches existingRecord.Name` because of the missing domain suffix.
