### ISSUE TITLE
[Question] DNSRecord dynamic IP address ?

### ISSUE THREAD

**Issue by edenreich** [replicatedhq/kubeflare#28]
Hey,

Not an issue, more like a question...
I found this project interesting just before I was planning to build a kubernetes operator for Cloudflare myself. I have a very specific use case but I think it could be useful for some.

I came up with the following idea around 2 years ago: https://github.com/edenreich/cloudflare-dns-updater

My use-case is to run an on-premises web-server that listens for IP address changes by the Internet service provider, based on that I want to update the DNS record on cloudflare.

I think I might be able to use your operator but I'm not sure how I would go about it, therefore I would like to discuss with you different options, maybe we can introduce dynamic content ?

Something like:
```yaml
apiVersion: crds.kubeflare.io/v1alpha1
kind: DNSRecord
metadata:
  name: www.domainname.io
spec:
  zone: domainname.io
  record:
    type: "A"
    name: "www"
    content: "ISP" // magic keyword, would resolve to the NAT ip address
    proxied: true
    ttl: 3600
```

Or you'd rather keep it simple without dynamic content ?

Let me know what you think,

Thanks,
Eden
